apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "thermostat-chart.labels" . | nindent 4 }}
    thermostat: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http_port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    thermostat: backend
